### ISSUE TITLE
Нужно создать 1 класс, который будет описывать все тарифы

### ISSUE THREAD

**Issue by coursar** [Dinar-92/Tele2_Tariffs#1]
https://github.com/Dinar-92/Tele2_Tariffs_DZ-3_Kamaev/blob/05ecd9eb20fe18a3bbe3916d38fe3f1c16ed0034/src/My_online.java#L1-L15

**Comment by Dinar-92** [comment]
Думаю, я правильно сделал
https://github.com/Dinar-92/Tele2_Tariffs/tree/master/src

**Comment by Dinar-92** [comment]
Исправлено
https://github.com/Dinar-92/Tele2_Tariffs/blob/07bb91dc03e9433b4b817a97040e089db2a7047f/src/Tele2Tariff.java#L1-L27
